//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystem333.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string CommentText { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int SuggestionID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public int UserID { get; set; }
    
        public virtual suggestion suggestion { get; set; }
        public virtual user user { get; set; }
    }
}
