//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystem333.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suggestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suggestion()
        {
            this.users = new HashSet<user>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int ID_suggestion { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public int ID_status { get; set; }
        public string category { get; set; }
        public int ID_section { get; set; }
        public int ID_severity { get; set; }
        public string title { get; set; }
        public string priority { get; set; }
        public Nullable<System.DateTime> acceptedon { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<System.DateTime> resolvedon { get; set; }
        public string ticketno { get; set; }
        public string steps { get; set; }
        public string resolve { get; set; }
    
        public virtual section section { get; set; }
        public virtual severity severity { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
